
####---- Petrosius et al. 2023 ---####

library(SingleCellExperiment)
library(scp)
library(tidyverse)
dataDir <- "~/isilon/DataSets/SCPCBIO/SNEcomb_sc8227_ASTRAL/"

####---- Create sample annotation ----####

## Retrieve annotation files
facs <- read.csv(paste0(dataDir, "index_map.csv"))
map <- read.csv(paste0(dataDir, "msRuns_overview.csv"), row.names = "X")

## Map FACS data with MS runs
facs_mapped <- inner_join(map, facs, by = "Well")

## Create metadata
meta <-
  facs_mapped |>
  mutate(filename = sub(".*RunSummaries/", "", filename),
         filename = sub(".raw.*", "", filename),
         fileID = paste(CellType, Cell.Number, sep = "_"),
         quant = "quant") |>
  select(-Cell.Type) |>
  arrange(by_group = CellType, Cell.Number)

colnames(meta) <- gsub("_$" , "", gsub("\\.+", "_", colnames(meta)))

####---- PSM data ----####

## PSM data has been shared by the authors in PEPQuant file from
## spectronaut

## Retrieve ID/quant file
psm <-
  read.delim(paste0(dataDir, "20240201_130747_PEPQuant (Normal).tsv"))

psm$fileID <- sub(".*sc8227_" , "", psm$R.FileName)

colnames(psm)[colnames(psm) == "FG.MS1Quantity"] <- "quant"

## QFeatures object
petrosius2023_AML <-
  readSCP(featureData = psm,
          colData = meta,
          batchCol = "fileID",
          channelCol = "quant",
          sep = "_")

####---- Generate peptide data ----####

## Peptide data is generated by aggregation of the psm data

petrosius2023_AML <-
  aggregateFeatures(petrosius2023_AML,
                    i = 1:length(petrosius2023_AML),
                    fcol = "PEP.StrippedSequence",
                    fun = colMedians,
                    name = paste0("peptide_", names(petrosius2023_AML)))

petrosius2023_AML <-
  joinAssays(petrosius2023_AML,
             i = grep("peptide", names(petrosius2023_AML)),
             name = "peptides")

petrosius2023_AML <-
  petrosius2023_AML[, , !grepl("peptide_", names(petrosius2023_AML))]


####---- Retrieve protein data ----####

## Protein data has been shared by the authors in a PGQuant file from
## spectronaut

prot <-
  read.delim(paste0(dataDir, "20240201_130747_PGQuant (Normal).tsv"))

prot$R.FileName <- sub(".*Bremen/" , "", prot$R.Raw.File.Name)
prot$R.FileName <- sub(".raw" , "", prot$R.FileName)
prot$fileID <- sub(".*sc8227_" , "", prot$R.FileName)

colnames(prot)[colnames(prot) == "PG.Quantity"] <- "quant"

## Pivot to wide format
prot <- prot |>
  select(PG.Genes, PG.ProteinAccessions, PG.ProteinDescriptions,
         quant, fileID) |>
  pivot_wider(names_from = fileID,
              values_from = quant,
              names_glue = "{fileID}_quant")

## Read as SingleCellExperiment object
prot_assay <-
  readSingleCellExperiment(prot,
                           ecol = colnames(prot)[grep("quant",
                                                      colnames(prot))],
                           fnames = "PG.ProteinAccessions")

## Add assay to petrosius2023_AML object
petrosius2023_AML <-
  addAssay(petrosius2023_AML,
           prot_assay,
           name = "proteins")

## Add link from peptide data to protein data
petrosius2023_AML <- addAssayLink(petrosius2023_AML,
                              from = "peptides",
                              to = "proteins",
                              varFrom = "PG.ProteinAccessions",
                              varTo = "PG.ProteinAccessions")

# Save data as Rda file
save(petrosius2023_AML,
     file = "~/2022-phd-samuel-gregoire/petrosius2023_AML.Rda",
     compress = "xz",
     compression_level = 9)
