##' Fulcher et al. 2026 (bioRxiv): human PBMCs.
##'
##' Single-cell proteomic data from peripheral blood mononuclear cells
##' (PBMCs) collected, isolated using the cellenONE, prepared using
##' the N2 nanoPOTS technology, acquired with a ThermoFisher Orbitrap
##' Eclipse Tribrid and searchd with FragPipe. Single cells were
##' multiplexed using TMTpro 32-plex reagents (although 35 TMT
##' reagents/set were found in the data). Cell types are not defined
##' prior to data acquisition, but the data set also contains samples
##' for boosting peptide identification ("Bridge"), empty sample for
##' QC ("Blank") and empty samples that isotopically adjacent to
##' bridge samples ("Isotope"). The data set contains data at the
##' peptide and protein level as provided by the authors, but also
##' modelled protein data using the scplainer approach.
##'
##' @format A [QFeatures] object with 3 assays, each assay inheriting 
##' from the [SummarizedExperiment] class:
##'
##' - `peptides`: formatted data generated by FragPipe
##' (`abundance_peptide_None.tsv`), containing 8,723 peptides for
##' 2,485 samples (mostly single cells, see annotations below).
##' - `proteins`: same as the peptide data, but for proteins (using
##' FragPipe's `abundance_protein_None.tsv` table).
##' - `peptides_modelled`: same as peptides, but after minimal data
##' processing and scplainer data modelling (see below).
##'
##' The `colData(petrosier2026())` contains the sample annotations: 
##' - SampleName: sample ID as encoded by the authors for the FragPipe
##' search 
##' - PoolId: the TMT set identifier
##' - Well: the well coordinate on the MS injection plate
##' - Channel: the TMT reagent used for multiplexing
##' - Chip: the N2 chip identifier
##' - ChannelType: the type of channel, either single cells (n = 1988); 
##' bridge samples (n = 142); blank samples (n = 213) or blank samples
##' that are isotopically adjacent to bridge samples(n = 142). Note
##' that each set contains 2 bridge samples: one deuterated
##' (TMT-135ND) and one non-deuterated (TMT-126).
##' - LC: liquid chromatography column
##' - RemovedByAuthors: FALSE if the sample ID is listed in the
##' metadata file retrieved from the author's [Github
##' repository](https://github.com/Cajun-data/RTLS-and-TMT32-scProteomics-of-PBMCs/blob/main/Single_PBMCs_Fig4/Metadata/First_Pass_PBMCs_KEEP.csv).
##' - quantCols: used to format the input table as QFeatures object.
##' - NPeptides: number of peptides identified in each sample
##' - NProteins: number of proteins identified in each sample
##' - MedianIntensity: median peptides intensity in each sample
##'
##' @section Acquisition protocol:
##'
##' The data were acquired using the following setup. More information
##' can be found in the source article (see *References*).
##'
##' - **Sample collection**: Blood samples taken from healthy donors
##' and PBMCs were extracted.
##' - **Cell isolation**: Cell were isolated using a cellenONE sorter
##' and dispensed on in-house N2 nanoPOTS chips (array of 48 nanowells
##' containing 32 inner wells each). 
##' - **Sample preparation** Single-cell protein lysates were digested
##'   overnight at 37°C in a digestion buffer containing DDM and 1/2
##'   Lys-C/Trypsin. Subsequently, TMT reagents
##' diluted in DMSO were added and incubated overnight. Labelling was
##' quenched using HA with DTT. Sample were acidified using formic
##' acid.
##' - **Liquid chromatography**: Chromatographic separation of peptides
##'   was conducted using a home-built dual-column nanoPOTS
##'   autosampler. The LC consists of a parallel setup with an
##'   in-house packed solide phase extracton (100µm i.d., 4cm, 5µm
##'   C18) and an in-house pached LC column (50µm i.d., 25 cm, 1.7µm
##'   C18), operatd with an Ultimate 3000 RSLC nano Systems
##' - **Mass spectrometry**: Acquisition was conducted with an Orbitrap
##'   Eclipse Tribrid with FAIMS. We refere to the original preprint
##'   for in-depth details on the MS settings
##' - **Raw data processing**: Raw files were processed using
##'   FragPipe v23.0 (MSFragger v4.3; MSBooster v1.3.9; Percolator
##'   v3.7.1; Philosopher 5.1.1; IonQuant 1.11.11; TMT-Integrator
##'   6.1.1). TMTpro reagents were set as static modificaton and
##'   M-oxidation as variable modification. 
##'
##' @section Data collection:
##'
##' The data were provided by the authors and is accessible at the
##' following [Zenodo repository](TODO: add Zenodo link). 
##' The repository contains the following files of interest:
##'
##' The sample names were extracted from FragPipe's output table and
##' some annotations were derived from the names (PoolId, Well,
##' Channel, Chip, ChannelType). The LC information and which samples
##' to remove was provided by the author as metadata and included in
##' the annotations. The peptide table (`abundance_peptide_None.tsv`),
##' along with the extracted annotations, were combined in a single
##' [QFeatures] object using the [scp::readSCP()] function.
##'
##' The protein table (`abundance_protein_None.tsv`) were formatted
##' formated using [QFeatures::readSummarizedExperiment()] and added
##' to the QFeatures object. 
##' 
##' The peptide_modelled set was generated from the `peptides` set.
##' First, the data were filtered to keep only single cells that were
##' retained by the authors (cf batch effect discussed in Fig S4 in
##' the preprint).  Then, the data was minimally processed (encoding
##' 0s as NA, log-transformation). Finally, an scplainer model was
##' fit, which includes the median intensity as a normalisation
##' factor, and TMT reagent and TMT set identifier as technical
##' factor. An N/P threshold of 5 was applied. 
##'
##' @source 
##'
##' All data can be from the [Zenodo repository](TODO). Data sources
##' were identified from the preprint's data availability statement:
##'   
##' | Data Id         | Description               | Source
##' |-----------------|---------------------------|-------
##' | github          | Code and metadata         | https://github.com/Cajun-data/RTLS-and-TMT32-scProteomics-of-PBMCs/tree/V1
##' | msv000100684    | FragPipe output           | ftp://massive-ftp.ucsd.edu/v12/MSV000100684/
##' | zenodo_18421469 | CellenOne output          | https://zenodo.org/records/18421469
##' | zenodo_18421672 | Authors intermediate data | https://zenodo.org/records/18421672
##' 
##' @references
##'
##' Fulcher, J. M., Kwon, Y., Dawar, P., Kumar, R., Williams, S. M., 
##' Miller, P., ... Paša-Tolić, L. (2026). Single-cell proteomics of
##' human peripheral blood mononuclear cells exceeding 600 cells per
##' day. doi:10.64898/2026.02.01.703169
##'
##' @examples
##' \donttest{
##' fulcher2026()
##' }
##'
##' @keywords datasets
##'
"fulcher2026"
